apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books-api-staging-oci
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/parraletz/charts/books-api
      targetRevision: ' v3.2.0'
      chart: books-api
      path: .
      helm:
        releaseName: books-api
        valuesObject:
          image:
            tag: ' v3.2.0'
            repository: ghcr.io/parraletz/books-api
            # valuesFiles:
            #   - $values/books/api/values-staging.yaml
    - repoURL: git@github.com:parraletz/gitops-cf.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: books-api-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
